### DISCUSSION TITLE
Is there any way to set env in plugins.toml?

### DISCUSSION THREAD

**Discussion by xiaoxiangmoe** [rossmacarthur/sheldon#190] [Q&A]
This is my zsh config
```sh
# .zshrc
ZSH_THEME=agnoster
ZSH_THEME="robbyrussell" plugins=(git npm macos) eval "$(sheldon source)" # see https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#enabling-plugins
echo $ZSH_THEME # the ZSH_THEME value should keep agnoster here
```
```toml
# .config/sheldon/plugins.toml
shell = "zsh"
[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
```

Is there any way to move config `ZSH_THEME="robbyrussell" plugins=(git npm macos) ` from `.zshrc` to `.config/sheldon/plugins.toml`?

```toml
# .config/sheldon/plugins.toml
shell = "zsh"
[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
```
