### ISSUE TITLE
Check local plugins each time `sheldon source` is run

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#102]
### The problem

Consider the following config.

```toml
[plugins.myplugin]
local = "~/.zsh/myplugin"
use = "*.zsh"  # use all files matching `*.zsh`
```

where `~/.zsh/myplugin` contains `x.zsh`.

When sheldon runs for the first time it will generate a lock file that references `x.zsh`. If a new file `y.zsh` is added to this directory sheldon will not discover it unless the user explicitly runs `sheldon lock`.

### Proposed solution

Local plugins are inexpensive to check and are much more likely to change between sheldon runs. Sheldon could completely recheck these plugins each time `sheldon source` is run.

### Unresolved questions

1. Should this be configurable?
2. Should this be opt in or opt out?
3. Would there be any perceived overhead to checking this?
