### ISSUE TITLE
Silently failing when no files are matched for a plugin

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#103]
If you configure a plugin that uses a template that uses `{{ file }}` or `each = true` then if no files are matched we should fail. At the moment sheldon appears to silently not care about this.

Basically this type of lock file should not be generated

```toml
[[plugins]]
name = "pure"
source_dir = "/Users/ross/.sheldon/repos/github.com/rossmacarthur/pure"
files = []
apply = ["source"]
```
