### ISSUE TITLE
Zsh: consider first class support for `romkatv/zsh-defer`

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#105]
[romkatv/zsh-defer](https://github.com/romkatv/zsh-defer) is a great Zsh plugin that can basically give [zinit](https://github.com/zdharma/zinit)'s turbo mode to any plugin manager. It might be cool to provide support for deferring plugin sourcing out of the box using this plugin.

You can still very easily use this plugin using the following.

```toml
[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
```

And then you just have to add `apply = ["defer"]` to any plugin you want to `defer source ...`

I propose adding the following

- Add `defer` as default template
- if someone has not overriden `defer` and uses it then automatically add `romkatv/zsh-defer` as a plugin.
