### ISSUE TITLE
Sheldon not adding manually downloaded completions to zsh

### ISSUE THREAD

**Issue by sidmadala** [rossmacarthur/sheldon#114]
**Operating System:** MacOS Catalina 10.15.4

**Shell:** ZSH

**Issue:**

Sheldon will clone the Github repo and add it to the FPATH, but when opening a new shell none of the tab completions are available as they would be in Antigen. The only plugins that work are zsh-syntax-highlighting and zsh-autosuggestions. I have read the documentation and example dotfiles to try and resolve the issue, but nothing seems to work. I have attached my plugins.toml for reference. I would appreciate any assistance.

**Config:**

```toml
shell = "zsh"

# Default apply defer
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins]

# Non-deferred plugins 
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# Deferred plugins
[plugins.docker-zsh-completion]
github = "greymd/docker-zsh-completion"

[plugins.conda-zsh-completion]
github = "esc/conda-zsh-completion"

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath", "defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
```

**Comment by rossmacarthur** [comment]
Zsh completions require that you also call `compinit` after modifying the `fpath`. At present Sheldon does not do this for you. The easiest way to fix this would be to make sure `compinit` is called after you source your Sheldon plugins. However, since you are deferring the loading of plugins which modify the `fpath`, you will also need to defer the `compinit` call so that it happens after the plugins modify `fpath`.

You could simply add the following to the end of your `plugins.toml`

```toml
[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
```

Or if you prefer you could put it in your .zshrc file.

```sh
source <(sheldon source)
autoload -Uz compinit &&  zsh-defer compinit
```

Note: since `compinit` does the actual work of loading the completions you might want to consider only deferring this particular call, not the ones that just modify `fpath`. 

Hope this helps 😄
