### ISSUE TITLE
Broken symlink seems to break lock file without erroring

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#120]
```toml
[plugins.test]
local = "~/dir/with/broken/symlink/*"
```
