### ISSUE TITLE
Rename remote file

### ISSUE THREAD

**Issue by ThibaultNocchi** [rossmacarthur/sheldon#125]
Hello, thanks for your tool!

I'm downloading a ZSH completion file with the remote plugin, but it seems to need to be renamed to be applied by OMZ.

Is it possible to do this?

Thanks!

**Comment by rossmacarthur** [comment]
You can apply an arbitrary template to symlink the downloaded file to a folder that Oh My Zsh will load the completion from. For example assuming `$ZSH` is your Oh My Zsh installation and `$ZSH/completions` exists:

```toml
[templates]
symlink = { value = 'ln -s "{{ file }}" "$ZSH/completions/_{{ name }}"', each = true }

[plugins.myplugin]
remote = "https://myplugin.example.com/file"
apply = ["symlink"]
```
