### ISSUE TITLE
Extend remote to support `apply` and renaming of files

### ISSUE THREAD

**Issue by chopfitzroy** [rossmacarthur/sheldon#154]
Would it be possible to extend the [remote](https://sheldon.cli.rs/Configuration.html#remote) option to support renaming of files and using things like `apply`?

Ideally I would be able to do something like this:

```toml
[plugins.sheldon]
remote= "https://github.com/rossmacarthur/sheldon/blob/trunk/completions/sheldon.zsh"
file = "_sheldon"
apply = ["fpath"]
```

There are a number of repositories that have Zsh completions defined in files with names `command.zsh` or similar, from my understanding completions must always be defined as `_command`. A couple of examples:

- https://github.com/rossmacarthur/sheldon/blob/trunk/completions/sheldon.zsh
- https://github.com/sharkdp/bat/blob/master/assets/completions/bat.zsh.in
- https://github.com/RichiH/vcsh/blob/main/completions/vcsh.zsh

I was hoping it would be possible to extend `remote` to support renaming of files and `apply`.

**Comment by rossmacarthur** [comment]
So sheldon allows you to configure the install using templates. I'm wondering if that would work for you?

### Symlink method

You could symlink the completion file to an existing directory and add that location to the `fpath`.

```toml
# sheldon 0.7.x config file

[templates]
completion = "ln -sf {{ files.0 }} /path/to/completions/_{{ name }}"  # only uses first matched file

[plugins.sheldon]
remote = "https://github.com/rossmacarthur/sheldon/blob/trunk/completions/sheldon.zsh"
apply = ["completion"]

[plugins.bat]
remote = "https://github.com/sharkdp/bat/blob/master/assets/completions/bat.zsh.in"
apply = ["completion"]

[plugins.vcsh]
remote = "https://github.com/RichiH/vcsh/blob/main/completions/vcsh.zsh"
apply = ["completion"]

[plugins.fpath]
inline = "fpath=( /path/to/completions $path )"
```

You can verify the generated script by running `sheldon source` manually
