### ISSUE TITLE
Unable to use zsh-completions in sheldon

### ISSUE THREAD

**Issue by KrozT** [rossmacarthur/sheldon#172]
Hello, I'm encountering an issue with the integration of zsh-completions in Sheldon. Despite multiple attempts, I can't seem to get it to work, and I'm unsure if I'm overlooking something or if there's an underlying error causing the problem.

***.zshrc***
```.zshrc
# Added by RTX
eval "$(rtx activate zsh)"

# Added by Starship
export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"
eval "$(starship init zsh)"

# Added by Sheldon
eval "$(sheldon source)"
```

I also tried changing the ***sheldon*** part but it still doesn't work:
```.zshrc
autoload -Uz compinit
eval "$(sheldon source)"
compinit
```

***plugins.toml***
```toml
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'
```

I also tried changing the ***plugins.compinit*** but it still doesn't work:
```toml
[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"
```

**Comment by 0xAbdiiii** [comment]
hi, I'm having the same issue. i would like to know how you solved it as i have been searching on the internet for over 12 hours now and i can't find anything about it.

**Comment by KrozT** [comment]
> hi, I'm having the same issue. i would like to know how you solved it as i have been searching on the internet for over 12 hours now and i can't find anything about it.

Hi, I was able to fix it some time later, I think I was configuring things wrong, this is how it currently works for me.

***plugins.toml***
```.zshrc
# Added for ZSH Completions
zstyle ':completion:*' menu yes select

fpath=(
  # Path for completion functions of non-Homebrew packages
  ~/.local/share/zsh/site-functions
  # Path for completion functions of Homebrew packages
  "$(brew --prefix)/share/zsh/site-functions"
  # Append existing completion paths
  $fpath
)

# Added by Sheldon
eval "$(sheldon source)"
```

**Comment by KrozT** [comment]
> hi, I'm having the same issue. i would like to know how you solved it as i have been searching on the internet for over 12 hours now and i can't find anything about it.

Hi, I was able to fix it some time later, I think I was configuring things wrong, this is how it currently works for me.

***.zshrc***
```.zshrc
# Added for ZSH Completions
zstyle ':completion:*' menu yes select

fpath=(
  # Path for completion functions of non-Homebrew packages
  ~/.local/share/zsh/site-functions
  # Path for completion functions of Homebrew packages
  "$(brew --prefix)/share/zsh/site-functions"
  # Append existing completion paths
  $fpath
)

# Added by Sheldon
eval "$(sheldon source)"
```

***plugins.toml***
```toml
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath", "defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'
```
