### ISSUE TITLE
Aliases set by plugin cannot be executed from other plugins

### ISSUE THREAD

**Issue by celclow** [rossmacarthur/sheldon#174]
It seems that aliases set by a plugin cannot be executed by other plugins. Since functions can be executed, I would expect aliases to be similarly executable.

plugins.toml
```toml
shell = "zsh"

[plugins]

[plugins.foo]
local = "~/foo"

[plugins.foo.hooks]
post = "aliastest ; functest"

[plugins.bar]
inline = "aliastest ; functest"
```

~/foo/foo.zsh
```sh
alias aliastest="echo aliastest"
functest() {echo "functest"}
```

Login log
functest can be executed from hooks.post and other plugins, whereas aliastest cannot be executed.
```
Last login: Tue Jan 23 13:23:34 on ttys001
(eval):2: command not found: aliastest # foo.hooks.post aliastest
functest                               # foo.hooks.post functest
(eval):3: command not found: aliastest # bar.inline aliastest
functest                               # bar.inline functest
% aliastest
aliastest
% functest
functest
```

zsh version: zsh 5.9 (x86_64-apple-darwin23.0)
sheldon version: sheldon 0.7.4
