### ISSUE TITLE
Sourcing plugins which are the output of an exectuable, e.g. starship.rs or atuin

### ISSUE THREAD

**Issue by elazarl** [rossmacarthur/sheldon#178]
Hi,

Is managing shell plugins which are based on installing an executable, possible with `sheldon`?

Is it within the scope of the project?

Something like

```toml
[plugins.atuin]
exec = "atuin init {{MYSHELL}}"
```

Which would execute the given command, and source the output.

If that within the project's scope, I'll be happy to open a PR.
