### ISSUE TITLE
Environment variable expansion in config

### ISSUE THREAD

**Issue by TeeSeal** [rossmacarthur/sheldon#182]
Example:
```toml
[plugin.example]
local = "$ZDOTDIR/plugins"
```

Ability to use environment variables for local plugin paths would make the sheldon config more portable (i.e. adds ability to use the same config on multiple systems that don't necessarily have the same directory structure).

Local plugins would probably be the most used case, but this could also be useful for other configuration options in some situations. For example:
```toml
[plugin.private-plugin]
git = "https://$PIRVATE_GIT_HOST/owner/repo"
```
I can see that a type of templating is already being used in some configuration fields so that can probably be re-used instead of using the the shell syntax:
```toml
[plugin.example]
local = "{{ env.ZDOTDIR }}/plugins"
```

I've looked through the documentation and couldn't find anything similar but do let me know if something like this is achievable with the current feature set.
