### ISSUE TITLE
[Feature] Build hook to be called after cloning

### ISSUE THREAD

**Issue by marcosmoura** [rossmacarthur/sheldon#189]
A few plugins that adds completions to a shell have an "install" process.

Example:
https://github.com/g-plane/pnpm-shell-completion
[install.zsh](https://github.com/g-plane/pnpm-shell-completion/blob/main/install.zsh) generates a completion bin file that will later be used by the [pnpm-shell-completion.plugin.zsh](https://github.com/g-plane/pnpm-shell-completion/blob/main/pnpm-shell-completion.plugin.zsh) plugin file (that can be loaded by Sheldon).

Unless I am missing something, currently there is no way to execute that `install.zsh` file after cloning the repo.

My request here would be having some sort of hook to be called for `build` purposes. Something like that:

``` toml
[plugins.pnpm-completion]
github = "g-plane/pnpm-shell-completion"

[plugins.pnpm-completion.hooks]
build = "install.sh"
```

**Comment by galou** [comment]
I'd also need this feature. I tried to replace with install hook but didn't work neither as `pre` nor `post`:
```toml
[plugins.zsh-yarn-autocompletions]
github = "g-plane/zsh-yarn-autocompletions"
use = ["yarn-autocompletions/yarn-autocompletions.plugin.zsh"]

[plugins.zsh-yarn-autocompletions.hooks]
pre = "pushd $HOME/.local/share/sheldon/repos/github.com/g-plane/zsh-yarn-autocompletions >/dev/null && cargo build --release && rm -rf yarn-autocompletions && mkdir yarn-autocompletions && ln -s ../yarn-autocompletions.plugin.zsh yarn-autocompletions/yarn-autocompletions.plugin.zsh && ln -s ../target/release/yarn-autocompletions yarn-autocompletions/yarn-autocompletions  && popd > /dev/null"
```
I got 
```
Loaded ~/.config/sheldon/plugins.toml
   [...]
    Cloned https://github.com/g-plane/zsh-yarn-autocompletions

error: failed to install plugin `zsh-yarn-autocompletions`
  due to: failed to find any files matching any of `["yarn-autocompletions/yarn-autocompletions.plugin.zsh"]`
```

The file is generated by the hook but sheldon probably requires it before runnning the pre hook. A build step would solve this.
