### ISSUE TITLE
Way to set env in plugins.toml

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#191]
### Discussed in https://github.com/rossmacarthur/sheldon/discussions/190

<div type='discussions-op-text'>

<sup>Originally posted by **xiaoxiangmoe** October 23, 2024</sup>
This is my zsh config
```sh
# .zshrc
ZSH_THEME=agnoster
ZSH_THEME="robbyrussell" plugins=(git npm macos) eval "$(sheldon source)" # see https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#enabling-plugins
echo $ZSH_THEME # the ZSH_THEME value should keep agnoster here
```
```toml
# .config/sheldon/plugins.toml
shell = "zsh"
[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
```

Is there any way to move config `ZSH_THEME="robbyrussell" plugins=(git npm macos) ` from `.zshrc` to `.config/sheldon/plugins.toml`?

```toml
# .config/sheldon/plugins.toml
shell = "zsh"
[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
```
</div>
