### ISSUE TITLE
Improve configuration usability

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#36]
**Removing the need for a `source` key**

We could use the name of the source type as the key (similar to what Cargo does).

Examples:

```toml
[plugins.pure]
git = "https://github.com/rossmacarthur/pure"
```

```toml
[plugins.pure]
github = "rossmacarthur/pure"
```

```toml
[plugins.pure]
gist = "579d02802b1cc17baed07753d09f5009"
```

**Improve git revision specification with `branch` and `tag` keys**

This actually makes our life easier when determining how to checkout the revision.

See [here](https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/utils.rs#L207) for how to better checkout.

```toml
[plugins.pure]
git = "https://github.com/rossmacarthur/pure"
branch = "other"
```

```toml
[plugins.pure]
git = "https://github.com/rossmacarthur/pure"
tag = "v1.9.0"
```
