### ISSUE TITLE
Ability to change directory for plugin

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#39]
Say for example you want to change the directory for sub directory of a downloaded source

The following might be nice

```toml
[plugins.pip]
github = 'robbyrussell/oh-my-zsh'
directory = 'plugins/pip'
apply = ['fpath']
```

At the moment you have to do the following

```toml
[templates]
fpath2 = { value = 'fpath=( "$(dirname "{{ filename }}")" $fpath )', each = true }

[plugins.pip]
github = 'robbyrussell/oh-my-zsh'
apply = ['fpath2']
```
