### ISSUE TITLE
Ability to deserialize `apply` and `use` keys as strings

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#40]
Example

```toml
[plugins.wd]
github = 'mfaerevaag/wd'
tag = 'v0.4.6'
use = '*.sh'
apply = 'fpath'
```
