### ISSUE TITLE
Support branch / tag / commit

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/sheldon#7]
```toml
[plugins.pure]
source = 'github'
repository = 'sindresorhus/pure'
at = 'v1.9.0'
```

or 

```toml
[plugins.pure]
source = 'github'
repository = 'sindresorhus/pure'
checkout = 'v1.9.0'
```
